# Generated by Django 3.1.7 on 2021-04-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=160)),
                ('nameOfEve', models.CharField(max_length=80)),
                ('descOfEve', models.CharField(max_length=240)),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scVarChar', models.CharField(default='dqczS7J9jL3KnvQHVTPv7nEqZ40Of52yEUqoSduP4FIyLGf2QMx6zAFHzILW', max_length=60)),
                ('username', models.CharField(max_length=60)),
                ('userEmail', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='UserEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.event')),
                ('userKey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dash.user')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='dash.UserEvent', to='dash.User'),
        ),
    ]
